# Generated by Django 5.0.6 on 2024-07-12 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_modelo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="modelo",
            name="carca",
        ),
        migrations.AddField(
            model_name="modelo",
            name="marca",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="modelos",
                to="core.marca",
            ),
        ),
        migrations.AlterField(
            model_name="modelo",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="modelos",
                to="core.categoria",
            ),
        ),
    ]
