# Generated by Django 5.0.6 on 2024-07-12 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_veiculo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="veiculo",
            name="descricao",
        ),
    ]
